name: CI/CD for nautible front app

on:
  push:
    branches: [ "develop","feature/*","hotfix/*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop # for azure oidc
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
